language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - gem install mailcatcher
  - mailcatcher
  - sudo apt-get update -q
  - sudo apt-get install -y imagemagick
  - printf "\n" | pecl install imagick
  - mysql -e 'create database codeception;' -utravis
  - travis_retry composer self-update
  - mv .env.example .env
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run functional
  - vendor/bin/codecept run unit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
