sudo: required
dist: trusty
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  # Manually install mysql 5.6 since the default is v5.5.
  - sudo apt-get update -qq
  - sudo apt-get install -qq mysql-server-5.6 mysql-client-5.6 mysql-client-core-5.6
  # Install and run Mailcatcher
  - gem install mailcatcher
  - mailcatcher -f -v > out.txt&
  # Install Imagick
  - sudo apt-get update -q
  - sudo apt-get install -y imagemagick
  - printf "\n" | pecl install imagick
  # Create the database for tests
  - mysql -e "CREATE DATABASE codeception;" -uroot
  - mysql -e "CREATE USER 'travis'@'localhost';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON codeception. * TO 'travis'@'localhost';" -uroot
  # Grab external dependencies
  - travis_retry composer self-update
  - mv .env.example .env
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run functional
  - vendor/bin/codecept run integration
  - vendor/bin/codecept run unit

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
