language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  # Uninstall MySQL 5.5
  - sudo apt-get remove mysql-server-5.5 mysql-server-core-5.5
  - sudo apt-get autoremove
  # Install MySQL 5.6
  - sudo apt-get install libaio1
  - wget -O mysql-5.6.17.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.17-debian6.0-x86_64.deb/from/http://cdn.mysql.com/
  - sudo dpkg -i mysql-5.6.17.deb
  - sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server
  - sudo ln -sf /opt/mysql/server-5.6/bin/* /usr/bin/
  # Update configuration for switch from 5.5 to 5.6
  - sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf
  - sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf
  - sudo sed -i'' 's/basedir[^=]\+=.*$/basedir = \/opt\/mysql\/server-5.6/' /etc/mysql/my.cnf
  - sudo /etc/init.d/mysql.server start
  # Install and run Mailcatcher
  - gem install mailcatcher
  - mailcatcher -f -v > out.txt&
  # Install Imagick
  - sudo apt-get update -q
  - sudo apt-get install -y imagemagick
  - printf "\n" | pecl install imagick
  # Create the database for tests
  - mysql -e 'create database codeception;' -utravis
  # Grab external dependencies
  - travis_retry composer self-update
  - mv .env.example .env
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run functional
  - vendor/bin/codecept run integration
  - vendor/bin/codecept run unit

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
